main: yy.zacharyguard.kukurbpluvo.Main
name: Kukurbpluvo
version: 0.1.0
author: Zachary Guard
description: Gxi pluvas kukurboj!
commands:
  bash:
    description: Make it rain gourds.
    usage: /bash [username]
    permission: bukkit.op
    permission-message: Only ops (those with bukkit.op permission) are authorized to bash.